version: '2'
services:
    storemonobasic-app:
        image: storemonobasic
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://storemonobasic-postgresql:5432/storemonobasic
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9090:9090
    storemonobasic-postgresql:
        extends:
            file: postgresql.yml
            service: storemonobasic-postgresql
